#stock
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "pdst001"
  path = "/v1/product/stock"
  method = "GET"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "read-stock"
  path = "/v1/product/stock"
  method = "GET"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "update-stock"
  path = "/v1/product/stock"
  method = "PUT"

#item
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "read-item"
  path = "/v1/product/item"
  method = "GET"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "create-item"
  path = "/v1/product/item"
  method = "POST"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "update-item"
  path = "/v1/product/item"
  method = "PUT"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "delete-item"
  path = "/v1/product/item"
  method = "DELETE"

  

#product-group
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "read-product-group"
  path = "/v1/product/product-group"
  method = "GET"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "create-product-group"
  path = "/v1/product/product-group"
  method = "POST"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "update-product-group"
  path = "/v1/product/product-group"
  method = "PUT"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "delete-product-group"
  path = "/v1/product/product-group"
  method = "DELETE"

#sale-channel
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "read-sale-channel"
  path = "/v1/sale/channel"
  method = "GET"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "create-sale-channel"
  path = "/v1/sale/channel"
  method = "POST"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "update-sale-channel"
  path = "/v1/sale/channel"
  method = "PUT"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "delete-sale-channel"
  path = "/v1/sale/channel"
  method = "DELETE"

#sale-order
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "read-sale-order"
  path = "/v1/sale/order"
  method = "GET"

[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "create-sale-order"
  path = "/v1/sale/order"
  method = "POST"


#migrate
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "auto-migrate"
  path = "/v1/migrate/auto-migrate"
  method = "GET"

#index
[[httpRoutes]]
  url = "http://deploy-go-backend-1"
  port = 9997
  serviceId = "get-index"
  path = "/v1/index"
  method = "GET"


